### ISSUE TITLE
Unhandled exception executing command 'ar' in plugin Autorank v3.5.1

### ISSUE THREAD

**Issue by BlueSoapTurtle** [Armarr/AutoRank#2]
Getting this error whenever someone writes "/ar check" on some players
http://hastebin.com/ciqubeyema.sm

[Autorank] Enabling Autorank v3.5.1
[Stats] Enabling Stats v2.0.1-272

Guessing it has something to do with the versions I'm using.

**Comment by BlueSoapTurtle** [comment]
Why does it keep saying "BlueSoapTurtle opened this issue 2 days" ?

**Comment by Armarr** [comment]
Oh, you might wanna go post this on
https://github.com/Armarr/Autorank-2
this is the old repo before I rewrote my plugin. But Staartvin is maintaining it now and he doesn't get email notifications from this.

**Comment by BlueSoapTurtle** [comment]
Noticed that, thanks :) Also found the problem. switched to 3.4 AutoRank and it works :+1:
