### ISSUE TITLE
Auto rank is disabled! Please help!!!

### ISSUE THREAD

**Issue by ic3cr34m** [Armarr/AutoRank#3]
This is my configuration file: http://pastebin.com/gsacyuAG

It's gotta be something in the config. Please help me fix it.

**Comment by Armarr** [comment]
This is the repo for the legacy verrsion of autorank. Please post your issue here instead: https://github.com/Armarr/Autorank-2

But it's probably the space in the rank name of T. Senior. You have to put '-s around something with spaces or weird characters. So like 'T. Senior':
